/*------------------------------------------------------------------------------
* This is an autogenerated or copied file which AllSeen Alliance,
* as author hereby dedicates to the public domain.  Additionally, THIS
* SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND ANY CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
* AND OF GOOD TITLE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
* OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
* ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*------------------------------------------------------------------------------*/
////////////////////////////////////////////////////////////////////////////////
//
//  ALLJOYN MODELING TOOL - GENERATED CODE
//
////////////////////////////////////////////////////////////////////////////////
//
//  DO NOT EDIT
//
//  Add a category or subclass in separate .h/.m files to extend these classes
//
////////////////////////////////////////////////////////////////////////////////
//
//  AJNLSFControllerService.h
//
////////////////////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import "AJNBusAttachment.h"
#import "AJNBusInterface.h"
#import "AJNProxyBusObject.h"


////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceDelegate Bus Interface
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceDelegate <AJNBusInterface>


// properties
//
@property (nonatomic, readonly) NSNumber* ControllerServiceVersion;

// methods
//
- (NSNumber*)lightingResetControllerService:(AJNMessage *)methodCallMessage;
- (NSNumber*)getControllerServiceVersion:(AJNMessage *)methodCallMessage;

// signals
//
- (void)sendControllerServiceLightingResetInSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;


@end

////////////////////////////////////////////////////////////////////////////////

    
////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceDelegate Signal Handler Protocol
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceDelegateSignalHandler <AJNSignalHandler>

// signals
//
- (void)didReceiveControllerServiceLightingResetInSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;


@end

@interface AJNBusAttachment(LSFControllerServiceDelegate)

- (void)registerLSFControllerServiceDelegateSignalHandler:(id<LSFControllerServiceDelegateSignalHandler>)signalHandler;

@end

////////////////////////////////////////////////////////////////////////////////
    

////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceLampDelegate Bus Interface
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceLampDelegate <AJNBusInterface>


// properties
//
@property (nonatomic, readonly) NSNumber* LampVersion;

// methods
//
- (void)getAllLampIDsWithResponseCode:(NSNumber**)responseCode lampIDs:(AJNMessageArgument**)lampIDs message:(AJNMessage *)methodCallMessage;
- (void)getLampSupportedLangueagesWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID supportedLanguages:(AJNMessageArgument**)supportedLanguages message:(AJNMessage *)methodCallMessage;
- (void)getLampManufacturerWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language manufacturer:(NSString**)manufacturer message:(AJNMessage *)methodCallMessage;
- (void)getLampNameWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language lampName:(NSString**)lampName message:(AJNMessage *)methodCallMessage;
- (void)setLampNameWithLampID:(NSString*)lampID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language message:(AJNMessage *)methodCallMessage;
- (void)getLampDetailsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampDetails:(AJNMessageArgument**)lampDetails message:(AJNMessage *)methodCallMessage;
- (void)getLampParametersWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampParameters:(AJNMessageArgument**)lampParameters message:(AJNMessage *)methodCallMessage;
- (void)getLampParametersFieldWithLampID:(NSString*)lampID parameterFieldName:(NSString*)lampParameterFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID parameterFieldName:(NSString**)lampParameterFieldName parameterFieldValue:(NSString**)lampParameterFieldValue message:(AJNMessage *)methodCallMessage;
- (void)getLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampState:(AJNMessageArgument**)lampState message:(AJNMessage *)methodCallMessage;
- (void)getLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName stateFieldValue:(NSString**)lampStateFieldValue message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateWithLampID:(NSString*)lampID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampWithStateWithLampID:(NSString*)lampID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampWithPresetWithLampID:(NSString*)lampID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateToPresetWithLampID:(NSString*)lampID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName stateFieldValue:(NSString*)lampStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampStateFieldName:(NSString**)lampStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)resetLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)resetLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)getLampFaultsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFaults:(AJNMessageArgument**)lampFaults message:(AJNMessage *)methodCallMessage;
- (void)clearLampFaultsWithLampID:(NSString*)lampID lampFault:(NSNumber*)lampFault responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFault:(NSNumber**)lampFault message:(AJNMessage *)methodCallMessage;
- (void)getLampServiceVersionWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID version:(NSNumber**)lampServiceVersion message:(AJNMessage *)methodCallMessage;

// signals
//
- (void)sendlampNameDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)sendlampStateDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidFindLamp:(NSString*)LampID inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidLoseLamps:(AJNMessageArgument*)lampIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;


@end

////////////////////////////////////////////////////////////////////////////////

    
////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceLampDelegate Signal Handler Protocol
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceLampDelegateSignalHandler <AJNSignalHandler>

// signals
//
- (void)didReceivelampNameDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivelampStateDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivedidFindLamp:(NSString*)LampID inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivedidLoseLamps:(AJNMessageArgument*)lampIDs inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;


@end

@interface AJNBusAttachment(LSFControllerServiceLampDelegate)

- (void)registerLSFControllerServiceLampDelegateSignalHandler:(id<LSFControllerServiceLampDelegateSignalHandler>)signalHandler;

@end

////////////////////////////////////////////////////////////////////////////////
    

////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceLampGroupDelegate Bus Interface
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceLampGroupDelegate <AJNBusInterface>


// properties
//
@property (nonatomic, readonly) NSNumber* LampGroupVersion;

// methods
//
- (void)getAllLampGroupIDsWithResponseCode:(NSNumber**)responseCode lampGroupIDs:(AJNMessageArgument**)lampGroupIDs message:(AJNMessage *)methodCallMessage;
- (void)getLampGroupNameWithLampGroupID:(NSString*)lampGroupID language:(NSString*)language responseCode:(NSNumber**)responseCode lampIDGroupID:(NSString**)lampGroupID language:(NSString**)language lampGroupName:(NSString**)lampGroupName message:(AJNMessage *)methodCallMessage;
- (void)setLampGroupNameWithLampID:(NSString*)lampGroupID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language message:(AJNMessage *)methodCallMessage;
- (void)createLampGroupWithLampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs lampGroupName:(NSString*)lampGroupName language:(NSString*)language responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)updateLampGroupWithLampGroupID:(NSString*)lampGroupID lampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)deleteLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)getLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID lampID:(AJNMessageArgument**)lampID lampGroupIDs:(AJNMessageArgument**)lampGroupIDs message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateWithLampGroupID:(NSString*)lampGroupID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampGroupWithStateWithLampGroupID:(NSString*)lampGroupID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampGroupWithPresetWithLampGroupID:(NSString*)lampGroupID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateToPresetWithLampGroupID:(NSString*)lampGroupID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName groupStateFieldValue:(NSString*)lampGroupStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)resetLampGroupStateWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)resetLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName message:(AJNMessage *)methodCallMessage;

// signals
//
- (void)sendlampGroupNamesDidChangeForLampGroupIDs:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidCreateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidUpdateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidDeleteLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;


@end

////////////////////////////////////////////////////////////////////////////////

    
////////////////////////////////////////////////////////////////////////////////
//
// LSFControllerServiceLampGroupDelegate Signal Handler Protocol
//
////////////////////////////////////////////////////////////////////////////////

@protocol LSFControllerServiceLampGroupDelegateSignalHandler <AJNSignalHandler>

// signals
//
- (void)didReceivelampGroupNamesDidChangeForLampGroupIDs:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivedidCreateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivedidUpdateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;
- (void)didReceivedidDeleteLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId message:(AJNMessage *)signalMessage;


@end

@interface AJNBusAttachment(LSFControllerServiceLampGroupDelegate)

- (void)registerLSFControllerServiceLampGroupDelegateSignalHandler:(id<LSFControllerServiceLampGroupDelegateSignalHandler>)signalHandler;

@end

////////////////////////////////////////////////////////////////////////////////
    

////////////////////////////////////////////////////////////////////////////////
//
//  AJNLSFControllerServiceObject Bus Object superclass
//
////////////////////////////////////////////////////////////////////////////////

@interface AJNLSFControllerServiceObject : AJNBusObject<LSFControllerServiceDelegate, LSFControllerServiceLampDelegate, LSFControllerServiceLampGroupDelegate>

// properties
//
@property (nonatomic, readonly) NSNumber* ControllerServiceVersion;
@property (nonatomic, readonly) NSNumber* LampVersion;
@property (nonatomic, readonly) NSNumber* LampGroupVersion;


// methods
//
- (NSNumber*)lightingResetControllerService:(AJNMessage *)methodCallMessage;
- (NSNumber*)getControllerServiceVersion:(AJNMessage *)methodCallMessage;
- (void)getAllLampIDsWithResponseCode:(NSNumber**)responseCode lampIDs:(AJNMessageArgument**)lampIDs message:(AJNMessage *)methodCallMessage;
- (void)getLampSupportedLangueagesWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID supportedLanguages:(AJNMessageArgument**)supportedLanguages message:(AJNMessage *)methodCallMessage;
- (void)getLampManufacturerWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language manufacturer:(NSString**)manufacturer message:(AJNMessage *)methodCallMessage;
- (void)getLampNameWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language lampName:(NSString**)lampName message:(AJNMessage *)methodCallMessage;
- (void)setLampNameWithLampID:(NSString*)lampID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language message:(AJNMessage *)methodCallMessage;
- (void)getLampDetailsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampDetails:(AJNMessageArgument**)lampDetails message:(AJNMessage *)methodCallMessage;
- (void)getLampParametersWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampParameters:(AJNMessageArgument**)lampParameters message:(AJNMessage *)methodCallMessage;
- (void)getLampParametersFieldWithLampID:(NSString*)lampID parameterFieldName:(NSString*)lampParameterFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID parameterFieldName:(NSString**)lampParameterFieldName parameterFieldValue:(NSString**)lampParameterFieldValue message:(AJNMessage *)methodCallMessage;
- (void)getLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampState:(AJNMessageArgument**)lampState message:(AJNMessage *)methodCallMessage;
- (void)getLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName stateFieldValue:(NSString**)lampStateFieldValue message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateWithLampID:(NSString*)lampID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampWithStateWithLampID:(NSString*)lampID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampWithPresetWithLampID:(NSString*)lampID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateToPresetWithLampID:(NSString*)lampID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName stateFieldValue:(NSString*)lampStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampStateFieldName:(NSString**)lampStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)resetLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID message:(AJNMessage *)methodCallMessage;
- (void)resetLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)getLampFaultsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFaults:(AJNMessageArgument**)lampFaults message:(AJNMessage *)methodCallMessage;
- (void)clearLampFaultsWithLampID:(NSString*)lampID lampFault:(NSNumber*)lampFault responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFault:(NSNumber**)lampFault message:(AJNMessage *)methodCallMessage;
- (void)getLampServiceVersionWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID version:(NSNumber**)lampServiceVersion message:(AJNMessage *)methodCallMessage;
- (void)getAllLampGroupIDsWithResponseCode:(NSNumber**)responseCode lampGroupIDs:(AJNMessageArgument**)lampGroupIDs message:(AJNMessage *)methodCallMessage;
- (void)getLampGroupNameWithLampGroupID:(NSString*)lampGroupID language:(NSString*)language responseCode:(NSNumber**)responseCode lampIDGroupID:(NSString**)lampGroupID language:(NSString**)language lampGroupName:(NSString**)lampGroupName message:(AJNMessage *)methodCallMessage;
- (void)setLampGroupNameWithLampID:(NSString*)lampGroupID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language message:(AJNMessage *)methodCallMessage;
- (void)createLampGroupWithLampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs lampGroupName:(NSString*)lampGroupName language:(NSString*)language responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)updateLampGroupWithLampGroupID:(NSString*)lampGroupID lampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)deleteLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)getLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID lampID:(AJNMessageArgument**)lampID lampGroupIDs:(AJNMessageArgument**)lampGroupIDs message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateWithLampGroupID:(NSString*)lampGroupID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampGroupWithStateWithLampGroupID:(NSString*)lampGroupID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)pulseLampGroupWithPresetWithLampGroupID:(NSString*)lampGroupID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateToPresetWithLampGroupID:(NSString*)lampGroupID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)transitionLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName groupStateFieldValue:(NSString*)lampGroupStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName message:(AJNMessage *)methodCallMessage;
- (void)resetLampGroupStateWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID message:(AJNMessage *)methodCallMessage;
- (void)resetLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName message:(AJNMessage *)methodCallMessage;


// signals
//
- (void)sendControllerServiceLightingResetInSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)sendlampNameDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)sendlampStateDidChangeForLampID:(NSString*)LampID lampName:(NSString*)lampName inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidFindLamp:(NSString*)LampID inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidLoseLamps:(AJNMessageArgument*)lampIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)sendlampGroupNamesDidChangeForLampGroupIDs:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidCreateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidUpdateLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;
- (void)senddidDeleteLampGroups:(AJNMessageArgument*)lampGroupsIDs inSession:(AJNSessionId)sessionId toDestination:(NSString*)destinationPath;


@end

////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//
//  LSFControllerServiceObject Proxy
//
////////////////////////////////////////////////////////////////////////////////

@interface LSFControllerServiceObjectProxy : AJNProxyBusObject

// properties
//
@property (nonatomic, readonly) NSNumber* ControllerServiceVersion;
@property (nonatomic, readonly) NSNumber* LampVersion;
@property (nonatomic, readonly) NSNumber* LampGroupVersion;


// methods
//
- (NSNumber*)lightingResetControllerService;
- (NSNumber*)getControllerServiceVersion;
- (void)getAllLampIDsWithResponseCode:(NSNumber**)responseCode lampIDs:(AJNMessageArgument**)lampIDs;
- (void)getLampSupportedLangueagesWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID supportedLanguages:(AJNMessageArgument**)supportedLanguages;
- (void)getLampManufacturerWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language manufacturer:(NSString**)manufacturer;
- (void)getLampNameWithLampID:(NSString*)lampID language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language lampName:(NSString**)lampName;
- (void)setLampNameWithLampID:(NSString*)lampID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language;
- (void)getLampDetailsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampDetails:(AJNMessageArgument**)lampDetails;
- (void)getLampParametersWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampParameters:(AJNMessageArgument**)lampParameters;
- (void)getLampParametersFieldWithLampID:(NSString*)lampID parameterFieldName:(NSString*)lampParameterFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID parameterFieldName:(NSString**)lampParameterFieldName parameterFieldValue:(NSString**)lampParameterFieldValue;
- (void)getLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampState:(AJNMessageArgument**)lampState;
- (void)getLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName stateFieldValue:(NSString**)lampStateFieldValue;
- (void)transitionLampStateWithLampID:(NSString*)lampID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID;
- (void)pulseLampWithStateWithLampID:(NSString*)lampID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID;
- (void)pulseLampWithPresetWithLampID:(NSString*)lampID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID;
- (void)transitionLampStateToPresetWithLampID:(NSString*)lampID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID;
- (void)transitionLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName stateFieldValue:(NSString*)lampStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampStateFieldName:(NSString**)lampStateFieldName;
- (void)resetLampStateWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID;
- (void)resetLampStateFieldWithLampID:(NSString*)lampID stateFieldName:(NSString*)lampStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID stateFieldName:(NSString**)lampStateFieldName;
- (void)getLampFaultsWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFaults:(AJNMessageArgument**)lampFaults;
- (void)clearLampFaultsWithLampID:(NSString*)lampID lampFault:(NSNumber*)lampFault responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID lampFault:(NSNumber**)lampFault;
- (void)getLampServiceVersionWithLampID:(NSString*)lampIDresponseCode:(NSNumber**)responseCode lampID:(NSString**)lampID version:(NSNumber**)lampServiceVersion;
- (void)getAllLampGroupIDsWithResponseCode:(NSNumber**)responseCode lampGroupIDs:(AJNMessageArgument**)lampGroupIDs;
- (void)getLampGroupNameWithLampGroupID:(NSString*)lampGroupID language:(NSString*)language responseCode:(NSNumber**)responseCode lampIDGroupID:(NSString**)lampGroupID language:(NSString**)language lampGroupName:(NSString**)lampGroupName;
- (void)setLampGroupNameWithLampID:(NSString*)lampGroupID lampName:(NSString*)lampName language:(NSString*)language responseCode:(NSNumber**)responseCode lampID:(NSString**)lampID language:(NSString**)language;
- (void)createLampGroupWithLampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs lampGroupName:(NSString*)lampGroupName language:(NSString*)language responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)updateLampGroupWithLampGroupID:(NSString*)lampGroupID lampIDs:(AJNMessageArgument*)lampIDs lampGroupIDs:(AJNMessageArgument*)lampGroupIDs responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)deleteLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)getLampGroupWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID lampID:(AJNMessageArgument**)lampID lampGroupIDs:(AJNMessageArgument**)lampGroupIDs;
- (void)transitionLampGroupStateWithLampGroupID:(NSString*)lampGroupID lampState:(AJNMessageArgument*)lampState transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)pulseLampGroupWithStateWithLampGroupID:(NSString*)lampGroupID fromState:(AJNMessageArgument*)fromLampState toState:(AJNMessageArgument*)toLampState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)pulseLampGroupWithPresetWithLampGroupID:(NSString*)lampGroupID fromPresetID:(NSNumber*)fromPresetID toPresetID:(NSNumber*)toPresetID period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)transitionLampGroupStateToPresetWithLampGroupID:(NSString*)lampGroupID presetID:(NSNumber*)presetID transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)transitionLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName groupStateFieldValue:(NSString*)lampGroupStateFieldValue transitionPeriod:(NSNumber*)transitionPeriod responseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName;
- (void)resetLampGroupStateWithLampGroupID:(NSString*)lampGroupIDresponseCode:(NSNumber**)responseCode lampGroupID:(NSString**)lampGroupID;
- (void)resetLampGroupStateFieldWithLampGroupID:(NSString*)lampGroupID groupStateFieldName:(NSString*)lampGroupStateFieldName responseCode:(NSNumber**)responseCode lampID:(NSString**)lampGroupID groupStateFieldName:(NSString**)lampGroupStateFieldName;


@end

////////////////////////////////////////////////////////////////////////////////
