/*------------------------------------------------------------------------------
* This is an autogenerated or copied file which AllSeen Alliance,
* as author hereby dedicates to the public domain.  Additionally, THIS
* SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND ANY CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
* AND OF GOOD TITLE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
* OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
* ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*------------------------------------------------------------------------------*/
////////////////////////////////////////////////////////////////////////////////
//
//  ALLJOYN MODELING TOOL - GENERATED CODE
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//
//  LSFLamp.m
//
////////////////////////////////////////////////////////////////////////////////

#import "LSFLamp.h"

////////////////////////////////////////////////////////////////////////////////
//
//  Objective-C Bus Object implementation for LSFLampObject
//
////////////////////////////////////////////////////////////////////////////////

@implementation LSFLampObject

- (void)clearLampFaultWithFaultCode:(NSNumber*)LampFaultCode responseCode:(NSNumber**)LampResponseCode faultCode:(NSNumber**)LampFaultCode message:(AJNMessage *)methodCallMessage
{
    // TODO: complete the implementation of this method
    //
     @throw([NSException exceptionWithName:@"NotImplementedException" reason:@"You must implement this method" userInfo:nil]);   
}

- (NSNumber*)transitionLamsStateWithTimestamp:(NSNumber*)Timestamp newState:(AJNMessageArgument*)NewState transitionPeriod:(NSNumber*)TransitionPeriod message:(AJNMessage *)methodCallMessage
{
    // TODO: complete the implementation of this method
    //
     @throw([NSException exceptionWithName:@"NotImplementedException" reason:@"You must implement this method" userInfo:nil]);   
}

- (NSNumber*)applyPulseEffectWithFromState:(AJNMessageArgument*)FromState toState:(AJNMessageArgument*)ToState period:(NSNumber*)period duration:(NSNumber*)duration numPulses:(NSNumber*)numPulses timestamp:(NSNumber*)timestamp message:(AJNMessage *)methodCallMessage
{
    // TODO: complete the implementation of this method
    //
     @throw([NSException exceptionWithName:@"NotImplementedException" reason:@"You must implement this method" userInfo:nil]);   
}


@end

////////////////////////////////////////////////////////////////////////////////
