// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import CoreBluetooth;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol BluetoothManagerDelegate;
@class ParamConnect;
@class DetectDeviceInfo;
@class CBCentralManager;
@class CBPeripheral;
@class NSNumber;
@class NSError;

SWIFT_CLASS("_TtC8hitoeAPI16BluetoothManager")
@interface BluetoothManager : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate>
@property (nonatomic, readonly) NSInteger ConnectedCount;
@property (nonatomic, readonly) BOOL IsScanning;
+ (BluetoothManager * __nonnull)instance;
- (void)setDelegate:(id <BluetoothManagerDelegate> __nullable)delegate;
- (BOOL)connectPeripheral:(ParamConnect * __nonnull)connectParam;
- (void)disconnectPeripheralBySessionId:(NSString * __nonnull)sessionId;
- (BOOL)startScan:(NSInteger)scanningTimeMSec deviceFilter:(NSString * __nonnull)deviceFilter;
- (NSArray<DetectDeviceInfo *> * __nonnull)getDetectDeviceList;
- (NSInteger)startSendSavedData:(NSString * __nonnull)sessionId;
- (void)centralManagerDidUpdateState:(CBCentralManager * __nonnull)central;
- (void)centralManager:(CBCentralManager * __nonnull)central didDiscoverPeripheral:(CBPeripheral * __nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * __nonnull)advertisementData RSSI:(NSNumber * __nonnull)RSSI;
- (void)centralManager:(CBCentralManager * __nonnull)central didDisconnectPeripheral:(CBPeripheral * __nonnull)peripheral error:(NSError * __nullable)error;
- (void)centralManager:(CBCentralManager * __nonnull)central didConnectPeripheral:(CBPeripheral * __nonnull)peripheral;
- (void)centralManager:(CBCentralManager * __nonnull)central didFailToConnectPeripheral:(CBPeripheral * __nonnull)peripheral error:(NSError * __nullable)error;
@end


SWIFT_PROTOCOL("_TtP8hitoeAPI24BluetoothManagerDelegate_")
@protocol BluetoothManagerDelegate
- (void)bluetoothManagerFinishScan;
- (void)tryConnectPeripheralFinish:(NSString * __nonnull)identifier result:(NSInteger)result sessionId:(NSString * __nullable)sessionId;
- (void)disconnectPeripheral:(NSString * __nonnull)identifier sessionId:(NSString * __nullable)sessionId;
@end


SWIFT_CLASS("_TtC8hitoeAPI16DetectDeviceInfo")
@interface DetectDeviceInfo : NSObject
@property (nonatomic, copy) NSString * __nonnull setDeviceName;
@property (nonatomic, copy) NSString * __nonnull setIdentifier;
@end


SWIFT_CLASS("_TtC8hitoeAPI12ParamConnect")
@interface ParamConnect : NSObject
@property (nonatomic, copy) NSString * __nonnull DeviceIdentifierNative;
@property (nonatomic, copy) NSString * __nonnull DeviceIdentifier;
@property (nonatomic, copy) NSString * __nonnull IndividualIdentifier;
@property (nonatomic) NSInteger ConnectMode;
@property (nonatomic) NSInteger RecordingData;
@property (nonatomic, copy) NSString * __nullable SessionId;
@property (nonatomic) NSInteger Pincode;
@property (nonatomic) NSInteger DisconnectRetryTime;
@property (nonatomic) NSInteger DisconnectRetryCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8hitoeAPI14SessionManager")
@interface SessionManager : NSObject
@property (nonatomic, readonly) BOOL IsTryConnectNow;
- (NSString * __nonnull)getTryConnectIdentifier;
- (void)setTryConnectIdentifier:(NSString * __nonnull)identifier;
- (NSString * __nullable)getSessionIdByIdentifier:(NSString * __nonnull)identifier;
- (BOOL)isExistSessionId:(NSString * __nonnull)sessionId;
- (NSString * __nullable)getIdentifierBySessionId:(NSString * __nonnull)sessionId;
- (NSString * __nullable)getSessionIdByConnectionId:(NSString * __nonnull)connectionId;
- (void)removeByIdentifier:(NSString * __nonnull)identifier;
- (BOOL)removeByConnectionId:(NSString * __nonnull)connectionId;
- (void)setSessionIdWithTypeWithConnectionId:(NSString * __nonnull)sessionId type:(NSInteger)type connectionId:(NSString * __nonnull)connectionId;
- (void)setConnectionIdDelegate:(NSString * __nonnull)connectionId delegate:(id __nonnull)delegate;
- (id __nullable)getDelegateByConnectionId:(NSString * __nonnull)connectionId;
- (id __nullable)getDelegateByConnectionIdExt:(NSString * __nonnull)connectionId;
- (void)removeConnectionIdDelegateByConnectionId:(NSString * __nonnull)connectionId;
- (BOOL)isExistConnectionTypeBySessionIdWithType:(NSString * __nonnull)sessionId type:(NSInteger)type;
- (void)setSessionIdWithIdentifier:(NSString * __nonnull)sessionId identifier:(NSString * __nonnull)identifier;
- (void)setExtConnectionIdWithDelegate:(NSString * __nonnull)connectionId delegate:(id __nonnull)delegate;
- (id __nullable)getExtGetDelegateByConnectionId:(NSString * __nonnull)connectionId;
- (void)removeExtConnectionId:(NSString * __nonnull)connectionId;
- (NSArray<NSString *> * __nonnull)getExtConnectionIds;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
